// Agradeço a Deus pelo dom do conhecimento
// Eduardo Marçal
// Código fonte criado em: 27/10/14
package desafio01;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Eduardo
 */
public class TelaCadastro extends javax.swing.JFrame {

    double salarioMinino = 724;
    String cargo;

    /**
     * Creates new form TelaCadastro
     */
    public TelaCadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupCargo = new javax.swing.ButtonGroup();
        jPanelTelaPrincipal = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableFuncionariosCadastrado = new javax.swing.JTable();
        jRadioButtonFuncTemporario = new javax.swing.JRadioButton();
        jRadioButtonFuncContratado = new javax.swing.JRadioButton();
        jRadioButtonEstagiario = new javax.swing.JRadioButton();
        jRadioButtonGerente = new javax.swing.JRadioButton();
        jLabelTituloDesafio = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jLabelIdade = new javax.swing.JLabel();
        jButtonCadastrar = new javax.swing.JButton();
        jLabelCategoria = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jTextFieldIdade = new javax.swing.JTextField();
        jLabelTituloPrograma = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableFuncionariosCadastrado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Idade", "Categoria", "Salario"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableFuncionariosCadastrado);

        buttonGroupCargo.add(jRadioButtonFuncTemporario);
        jRadioButtonFuncTemporario.setText("Funcionario Temporário");

        buttonGroupCargo.add(jRadioButtonFuncContratado);
        jRadioButtonFuncContratado.setText("Funcionário Contratado");

        buttonGroupCargo.add(jRadioButtonEstagiario);
        jRadioButtonEstagiario.setText("Estagiário");
        jRadioButtonEstagiario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonEstagiarioActionPerformed(evt);
            }
        });

        buttonGroupCargo.add(jRadioButtonGerente);
        jRadioButtonGerente.setText("Gerente");

        jLabelTituloDesafio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTituloDesafio.setText("Atividades 2014.2 - Desenvolvimento Desktop - Desafio 01");

        jLabelNome.setText("Nome:");

        jLabelIdade.setText("Idade:");

        jButtonCadastrar.setText("Cadastrar");
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarActionPerformed(evt);
            }
        });

        jLabelCategoria.setText("Categoria:");

        jLabelTituloPrograma.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTituloPrograma.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTituloPrograma.setText("Cadastramento de Funcionários");

        javax.swing.GroupLayout jPanelTelaPrincipalLayout = new javax.swing.GroupLayout(jPanelTelaPrincipal);
        jPanelTelaPrincipal.setLayout(jPanelTelaPrincipalLayout);
        jPanelTelaPrincipalLayout.setHorizontalGroup(
            jPanelTelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTelaPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanelTelaPrincipalLayout.createSequentialGroup()
                        .addComponent(jLabelNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelIdade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelTelaPrincipalLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabelTituloDesafio, javax.swing.GroupLayout.PREFERRED_SIZE, 716, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelTituloPrograma, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelTelaPrincipalLayout.createSequentialGroup()
                        .addGroup(jPanelTelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonCadastrar)
                            .addGroup(jPanelTelaPrincipalLayout.createSequentialGroup()
                                .addComponent(jLabelCategoria)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonGerente)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonFuncTemporario)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonFuncContratado)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonEstagiario)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelTelaPrincipalLayout.setVerticalGroup(
            jPanelTelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTelaPrincipalLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabelTituloDesafio)
                .addGap(18, 18, 18)
                .addComponent(jLabelTituloPrograma)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelTelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNome)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelIdade)
                    .addComponent(jTextFieldIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelTelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCategoria)
                    .addComponent(jRadioButtonGerente)
                    .addComponent(jRadioButtonFuncTemporario)
                    .addComponent(jRadioButtonFuncContratado)
                    .addComponent(jRadioButtonEstagiario))
                .addGap(18, 18, 18)
                .addComponent(jButtonCadastrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelTelaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelTelaPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed
        cadastar(new Funcionarios(jTextFieldNome.getText(), Integer.parseInt(jTextFieldIdade.getText()), comparaSalario(buttonGroupCargo)));
    }//GEN-LAST:event_jButtonCadastrarActionPerformed

    private void jRadioButtonEstagiarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonEstagiarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonEstagiarioActionPerformed

    public double comparaSalario(javax.swing.ButtonGroup buttonGroup) {

        if (buttonGroup.isSelected(jRadioButtonEstagiario.getModel())) {
            cargo = jRadioButtonEstagiario.getLabel();
            return 700;
        }
        if (buttonGroup.isSelected(jRadioButtonFuncContratado.getModel())) {
            cargo = jRadioButtonFuncContratado.getLabel();
            return salarioMinino * 2;
        }
        if (buttonGroup.isSelected(jRadioButtonFuncTemporario.getModel())) {
            cargo = jRadioButtonFuncTemporario.getLabel();
            return 60;
        }
        if (buttonGroup.isSelected(jRadioButtonGerente.getModel())) {
            cargo = jRadioButtonGerente.getLabel();
            return salarioMinino * 5;
        }
        return 0.0;
    }

    public void cadastar(Funcionarios funcionarios) {
        javax.swing.table.DefaultTableModel defaultTableModel
                = (DefaultTableModel) jTableFuncionariosCadastrado.getModel();
        defaultTableModel.addRow(new Object[]{funcionarios.nome, funcionarios.idade, cargo,funcionarios.salario});
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupCargo;
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JLabel jLabelCategoria;
    private javax.swing.JLabel jLabelIdade;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelTituloDesafio;
    private javax.swing.JLabel jLabelTituloPrograma;
    private javax.swing.JPanel jPanelTelaPrincipal;
    private javax.swing.JRadioButton jRadioButtonEstagiario;
    private javax.swing.JRadioButton jRadioButtonFuncContratado;
    private javax.swing.JRadioButton jRadioButtonFuncTemporario;
    private javax.swing.JRadioButton jRadioButtonGerente;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableFuncionariosCadastrado;
    private javax.swing.JTextField jTextFieldIdade;
    private javax.swing.JTextField jTextFieldNome;
    // End of variables declaration//GEN-END:variables
}
