/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package desafio05;

import javax.swing.JButton;

/**
 *
 * @author Eduardo
 */
public class Desafio05 extends javax.swing.JFrame {

    /**
     * Creates new form Desafio05
     */
    public Desafio05() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jRadioButtonEsporte = new javax.swing.JRadioButton();
        jRadioButtonComida = new javax.swing.JRadioButton();
        jRadioButtonHobby = new javax.swing.JRadioButton();
        jComboBoxEsporte = new javax.swing.JComboBox();
        jComboBoxComida = new javax.swing.JComboBox();
        jComboBoxHobby = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(300, 200));

        buttonGroup1.add(jRadioButtonEsporte);
        jRadioButtonEsporte.setText("Esporte");
        jRadioButtonEsporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonEsporteActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonComida);
        jRadioButtonComida.setText("Comida");
        jRadioButtonComida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonComidaActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonHobby);
        jRadioButtonHobby.setText("Hobby");
        jRadioButtonHobby.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonHobbyActionPerformed(evt);
            }
        });

        jComboBoxEsporte.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Futebool", "Volei", "Basket", "Tenis" }));
        jComboBoxEsporte.setVisible(false);

        jComboBoxComida.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pizza", "Lasanha", "Macarronada", "Patê" }));
        jComboBoxComida.setVisible(false);

        jComboBoxHobby.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Programação", "Caminhada", "Jogar Bola", "Assitir Filme" }));
        jComboBoxHobby.setVisible(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButtonHobby)
                        .addGap(24, 24, 24)
                        .addComponent(jComboBoxHobby, 0, 117, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButtonComida)
                        .addGap(20, 20, 20)
                        .addComponent(jComboBoxComida, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButtonEsporte)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxEsporte, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonEsporte)
                    .addComponent(jComboBoxEsporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonComida)
                    .addComponent(jComboBoxComida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonHobby)
                    .addComponent(jComboBoxHobby, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonEsporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonEsporteActionPerformed
        VerificaItemSelecionado();
    }//GEN-LAST:event_jRadioButtonEsporteActionPerformed

    private void jRadioButtonComidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonComidaActionPerformed
        VerificaItemSelecionado();
    }//GEN-LAST:event_jRadioButtonComidaActionPerformed

    private void jRadioButtonHobbyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonHobbyActionPerformed
        VerificaItemSelecionado();
    }//GEN-LAST:event_jRadioButtonHobbyActionPerformed
    public void VerificaItemSelecionado() {
        if (jRadioButtonEsporte.isSelected()) {
            jComboBoxEsporte.setVisible(true);
        } else {
            jComboBoxEsporte.setVisible(false);
        }
        
        if (jRadioButtonComida.isSelected()) {
            jComboBoxComida.setVisible(true);
        } else {
            jComboBoxComida.setVisible(false);
        }
        
        if (jRadioButtonHobby.isSelected()) {
            jComboBoxHobby.setVisible(true);
        } else {
            jComboBoxHobby.setVisible(false);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Desafio05.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Desafio05.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Desafio05.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Desafio05.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Desafio05().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox jComboBoxComida;
    private javax.swing.JComboBox jComboBoxEsporte;
    private javax.swing.JComboBox jComboBoxHobby;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonComida;
    private javax.swing.JRadioButton jRadioButtonEsporte;
    private javax.swing.JRadioButton jRadioButtonHobby;
    // End of variables declaration//GEN-END:variables
}
