/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto;

import arquivos.Gabarito;

/**
 *
 * @author Eduardo
 */
public class Resultado extends javax.swing.JFrame {

    /**
     * Creates new form Resultado
     */
    public Resultado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jLabelRespostaCamada1 = new javax.swing.JLabel();
        jLabelResultadoCamada1 = new javax.swing.JLabel();
        jLabelResultadoCamada2 = new javax.swing.JLabel();
        jLabelRespostaCamada2 = new javax.swing.JLabel();
        jLabelResultadoCamada3 = new javax.swing.JLabel();
        jLabelRespostaCamada3 = new javax.swing.JLabel();
        jLabelRespostaCamada4 = new javax.swing.JLabel();
        jLabelResultadoCamada4 = new javax.swing.JLabel();
        jLabelRespostaCamada5 = new javax.swing.JLabel();
        jLabelResultadoCamada5 = new javax.swing.JLabel();
        jLabelRespostaCamada6 = new javax.swing.JLabel();
        jLabelResultadoCamada6 = new javax.swing.JLabel();
        jLabelResultadoCamada7 = new javax.swing.JLabel();
        jLabelRespostaCamada7 = new javax.swing.JLabel();
        jLabelRespostaCamada8 = new javax.swing.JLabel();
        jLabelResultadoCamada8 = new javax.swing.JLabel();
        jLabelResultadoCamada9 = new javax.swing.JLabel();
        jLabelRespostaCamada9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabelPontosFinal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 500, 500));

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Gabarito"));

        jLabelRespostaCamada1.setText("Camada 1");

        jLabelResultadoCamada1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelResultadoCamada1.setText("Sua Resposta: ");

        jLabelResultadoCamada2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelResultadoCamada2.setText("Sua Resposta: ");

        jLabelRespostaCamada2.setText("Camada 2");

        jLabelResultadoCamada3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelResultadoCamada3.setText("Sua Resposta: ");

        jLabelRespostaCamada3.setText("Camada 2");

        jLabelRespostaCamada4.setText("Camada 2");

        jLabelResultadoCamada4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelResultadoCamada4.setText("Sua Resposta: ");

        jLabelRespostaCamada5.setText("Camada 3");

        jLabelResultadoCamada5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelResultadoCamada5.setText("Sua Resposta: ");

        jLabelRespostaCamada6.setText("Camada 4");

        jLabelResultadoCamada6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelResultadoCamada6.setText("Sua Resposta: ");

        jLabelResultadoCamada7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelResultadoCamada7.setText("Sua Resposta: ");

        jLabelRespostaCamada7.setText("Camada 5");

        jLabelRespostaCamada8.setText("Camada 6");

        jLabelResultadoCamada8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelResultadoCamada8.setText("Sua Resposta: ");

        jLabelResultadoCamada9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelResultadoCamada9.setText("Sua Resposta: ");

        jLabelRespostaCamada9.setText("Camada 7");

        jTextField1.setEnabled(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelResultadoCamada2)
                    .addComponent(jLabelRespostaCamada2)
                    .addComponent(jLabelResultadoCamada3)
                    .addComponent(jLabelRespostaCamada3)
                    .addComponent(jLabelRespostaCamada4)
                    .addComponent(jLabelResultadoCamada4)
                    .addComponent(jLabelRespostaCamada5)
                    .addComponent(jLabelResultadoCamada5)
                    .addComponent(jLabelRespostaCamada6)
                    .addComponent(jLabelResultadoCamada6)
                    .addComponent(jLabelResultadoCamada7)
                    .addComponent(jLabelRespostaCamada7)
                    .addComponent(jLabelRespostaCamada8)
                    .addComponent(jLabelResultadoCamada8)
                    .addComponent(jLabelResultadoCamada9)
                    .addComponent(jLabelRespostaCamada9)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelResultadoCamada1)
                            .addComponent(jLabelRespostaCamada1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabelRespostaCamada1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelResultadoCamada1)
                        .addGap(0, 3, Short.MAX_VALUE))
                    .addComponent(jTextField1))
                .addGap(18, 18, 18)
                .addComponent(jLabelRespostaCamada2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelResultadoCamada2)
                .addGap(21, 21, 21)
                .addComponent(jLabelRespostaCamada3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelResultadoCamada3)
                .addGap(21, 21, 21)
                .addComponent(jLabelRespostaCamada4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelResultadoCamada4)
                .addGap(21, 21, 21)
                .addComponent(jLabelRespostaCamada5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelResultadoCamada5)
                .addGap(21, 21, 21)
                .addComponent(jLabelRespostaCamada6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelResultadoCamada6)
                .addGap(21, 21, 21)
                .addComponent(jLabelRespostaCamada7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelResultadoCamada7)
                .addGap(21, 21, 21)
                .addComponent(jLabelRespostaCamada8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelResultadoCamada8)
                .addGap(21, 21, 21)
                .addComponent(jLabelRespostaCamada9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelResultadoCamada9)
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultado"));

        jLabelPontosFinal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelPontosFinal.setText("Pontos: 100");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(297, 297, 297)
                .addComponent(jLabelPontosFinal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(288, 288, 288))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelPontosFinal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        Gabarito gabarito = new Gabarito();
        jTextField1.setText(gabarito.camadaFisica());
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Resultado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Resultado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Resultado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Resultado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new Resultado().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelPontosFinal;
    private javax.swing.JLabel jLabelRespostaCamada1;
    private javax.swing.JLabel jLabelRespostaCamada2;
    private javax.swing.JLabel jLabelRespostaCamada3;
    private javax.swing.JLabel jLabelRespostaCamada4;
    private javax.swing.JLabel jLabelRespostaCamada5;
    private javax.swing.JLabel jLabelRespostaCamada6;
    private javax.swing.JLabel jLabelRespostaCamada7;
    private javax.swing.JLabel jLabelRespostaCamada8;
    private javax.swing.JLabel jLabelRespostaCamada9;
    private javax.swing.JLabel jLabelResultadoCamada1;
    private javax.swing.JLabel jLabelResultadoCamada2;
    private javax.swing.JLabel jLabelResultadoCamada3;
    private javax.swing.JLabel jLabelResultadoCamada4;
    private javax.swing.JLabel jLabelResultadoCamada5;
    private javax.swing.JLabel jLabelResultadoCamada6;
    private javax.swing.JLabel jLabelResultadoCamada7;
    private javax.swing.JLabel jLabelResultadoCamada8;
    private javax.swing.JLabel jLabelResultadoCamada9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

}
